spring:
  application:
    name: dsmeta
  datasource:
    url: jdbc:h2:mem:testdb
    username: 'sa'
    password: ''
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  twilio:
    account-sid: ${TWILIO_ACCOUNT_SID}
    auth-token: ${TWILIO_AUTH_TOKEN}
    phone-from: ${TWILIO_PHONE_FROM}
    phone-to: ${TWILIO_PHONE_TO}
